// Generated by CoffeeScript 1.6.3
/* example metadata
  {
    "actor":
    {
      "objectType": "person",
      "id": "f25d7eff-8859-49ed-85e9-e7c1f92bc334",
      "displayName": "anonymized"
    },
    "target":
    {
      "objectType": "conceptMap",
      "id": "9383fbbe-e071-49b2-9770-46ddc4f8cd6e",
      "displayName": "unnamed concept map"
    },
    "generator":
    {
      "objectType": "application",
      "url": document.URL,
      "id": "04123e9e-14d0-447b-a851-805b9262d9a6",
      "displayName": "ut.tools.conceptmapper"
    },
    "provider":
    {
      "objectType": "ils",
      "url": "http://graasp.epfl.ch/metawidget/1/b387b6f...",
      "id": "0f8184db-53ba-4868-9208-896c3d7c25bb",
      "inquiryPhase": "orientation"
      "displayName": "name-of-ils"
    }
  }
*/


(function() {
  "use strict";
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.golab = window.golab || {};

  window.golab.ils = window.golab.ils || {};

  window.golab.ils.metadata = window.golab.ils.metadata || {};

  window.golab.ils.metadata.MetadataHandler = (function() {
    function MetadataHandler(metadata, cb) {
      var _this = this;
      console.log("Initializing MetadataHandler.");
      if (metadata) {
        this._metadata = JSON.parse(JSON.stringify(metadata));
      } else {
        throw "MetadataHandler needs an initial set of metadata at construction!";
      }
      setTimeout(function() {
        if (cb) {
          return cb(null, _this);
        }
      }, 0);
      console.log("using metadata:");
      console.log(this._metadata);
      this;
    }

    MetadataHandler.prototype.setMetadata = function(newMetadata) {
      this._metadata = JSON.parse(JSON.stringify(newMetadata));
      return this;
    };

    MetadataHandler.prototype.getMetadata = function() {
      return this._metadata;
    };

    MetadataHandler.prototype.setActor = function(newActor) {
      return this._metadata.actor = newActor;
    };

    MetadataHandler.prototype.getActor = function() {
      return this._metadata.actor;
    };

    MetadataHandler.prototype.getTarget = function() {
      return this._metadata.target;
    };

    MetadataHandler.prototype.setTarget = function(newTarget) {
      return this._metadata.target = JSON.parse(JSON.stringify(newTarget));
    };

    MetadataHandler.prototype.getGenerator = function() {
      return this._metadata.generator;
    };

    MetadataHandler.prototype.getProvider = function() {
      return this._metadata.provider;
    };

    MetadataHandler.prototype.getTargetDisplayName = function() {
      return this._metadata.target.displayName;
    };

    MetadataHandler.prototype.setTargetDisplayName = function(newName) {
      return this._metadata.target.displayName = newName;
    };

    MetadataHandler.prototype.setTargetId = function(newId) {
      return this._metadata.target.id = newId;
    };

    return MetadataHandler;

  })();

  window.golab.ils.metadata.GoLabMetadataHandler = (function(_super) {
    __extends(GoLabMetadataHandler, _super);

    function GoLabMetadataHandler(metadata, cb) {
      var error,
        _this = this;
      if (typeof osapi !== "undefined" && osapi !== null) {
        console.log("Retrieving metadata from osapi/ils.");
        try {
          if (!$.cookie) {
            throw "jquery.cookie library needs to be present before using the (GoLab)MetadataHandler (needed by ILS library).";
          }
          if (!ils) {
            throw "ILS library needs to be present before using the (GoLab)MetadataHandler.";
          }
          ils.getCurrentUser(function(userResult) {
            if (userResult.error) {
              console.warn("error reading username:");
              console.warn(userResult.error);
              metadata.actor.displayName = "unknown";
            } else {
              metadata.actor.displayName = userResult;
            }
            return ils.getIls(function(ilsSpace, phaseSpace) {
              var actorId;
              console.log("GoLab-MetadataHandler: ilsSpace, phaseSpace:");
              console.log(ilsSpace);
              console.log(phaseSpace);
              metadata.generator.url = gadgets.util.getUrlParameters().url;
              if (ilsSpace != null) {
                metadata.provider.objectType = ilsSpace.spaceType;
                metadata.provider.id = ilsSpace.objectId;
                metadata.provider.displayName = ilsSpace.displayName;
              }
              metadata.provider.url = ilsSpace.profileUrl;
              if (phaseSpace != null) {
                metadata.provider.inquiryPhase = phaseSpace.displayName;
              }
              actorId = metadata.actor.displayName + "@" + metadata.provider.id;
              metadata.actor.id = actorId;
              GoLabMetadataHandler.__super__.constructor.call(_this, metadata);
              return cb(null, _this);
            });
          });
        } catch (_error) {
          error = _error;
          console.warn("error during metadata retrieval:");
          console.warn(error);
        }
      } else {
        console.log("Running outside osapi/ils, using given metadata.");
        GoLabMetadataHandler.__super__.constructor.call(this, metadata);
        cb(null, this);
      }
    }

    return GoLabMetadataHandler;

  })(window.golab.ils.metadata.MetadataHandler);

}).call(this);

/*
//@ sourceMappingURL=MetadataHandler.map
*/
